# Generated by Django 5.0.4 on 2024-04-26 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='users_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام بچه های گروه'),
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='نام دسته بندی ')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='گروه')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='کاربران')),
            ],
            options={
                'verbose_name': 'دسته بندی بجه های گروه',
                'verbose_name_plural': 'دسته بندی های بجه های گروه',
            },
        ),
    ]
