# Generated by Django 4.1 on 2024-05-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_group_users_to_make_group_alter_group_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='evil',
            field=models.BooleanField(default=False, verbose_name='نقشه ی شیطانی'),
        ),
    ]
