# Generated by Django 4.2.9 on 2024-06-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_group_evil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('0', 'شنبه'), ('1', 'یک شنبه'), ('2', 'دو شنبه'), ('3', 'سه شنبه'), ('4', 'چهار شنبه'), ('5', 'پنج شنبه'), ('6', 'جمعه')], max_length=1, unique=True, verbose_name='روز')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='days_selected',
            field=models.ManyToManyField(blank=True, to='group.day', verbose_name='روز های انتخابی'),
        ),
    ]
