# Generated by Django 4.2.9 on 2024-06-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_users_selected_days'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='users_selected_days',
            unique_together={('group', 'day')},
        ),
    ]
