# Generated by Django 4.2.9 on 2024-06-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_alter_users_selected_days_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.CharField(choices=[('شنبه', 'شنبه'), ('یک شنبه', 'یک شنبه'), ('دو شنبه', 'دو شنبه'), ('سه شنبه', 'سه شنبه'), ('چهار شنبه', 'چهار شنبه'), ('پنج شنبه', 'پنج شنبه'), ('جمعه', 'جمعه')], max_length=10, unique=True, verbose_name='روز'),
        ),
    ]
