# Generated by Django 4.2.9 on 2024-06-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_alter_day_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.CharField(choices=[('0', 'شنبه'), ('1', 'یک شنبه'), ('2', 'دو شنبه'), ('3', 'سه شنبه'), ('4', 'چهار شنبه'), ('5', 'پنج شنبه'), ('6', 'جمعه')], max_length=1, unique=True, verbose_name='روز'),
        ),
    ]
