# Generated by Django 4.2.14 on 2024-07-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_alter_day_day'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='users_selected_days',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='users_selected_days',
            name='day',
        ),
        migrations.RemoveField(
            model_name='users_selected_days',
            name='group',
        ),
        migrations.RemoveField(
            model_name='users_selected_days',
            name='users',
        ),
        migrations.RemoveField(
            model_name='group',
            name='days_selected',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Users_selected_days',
        ),
    ]
