# Generated by Django 4.2.14 on 2024-07-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_alter_users_selected_days_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='evil',
        ),
        migrations.AddField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='گروه جامعه ی شیراز'),
        ),
    ]
