# Generated by Django 5.0.4 on 2024-04-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id عددی')),
                ('username', models.CharField(blank=True, max_length=40, null=True, verbose_name='یوزرنیم تلگرام')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='نام')),
                ('is_dev', models.BooleanField(default=False, verbose_name='توسعه دهنده')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
    ]
