# Generated by Django 5.0.4 on 2024-04-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='صورت'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_main_admin',
            field=models.BooleanField(default=True, verbose_name='ادمین تمام'),
        ),
    ]
