# Generated by Django 4.2.14 on 2024-07-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_face_user_is_main_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='face',
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
