# Generated by Django 4.2.14 on 2024-07-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_face_user_instagram_id_user_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='message_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
