# Generated by Django 4.2.14 on 2024-07-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_message_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(blank=True, help_text='این فیلد توسط کاربر پر میشود', max_length=100, null=True, verbose_name='نام کامل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text='این فیلد توسط بات بر اساس نام تلگرام پر میشود', max_length=40, null=True, verbose_name='نام'),
        ),
    ]
